### ISSUE TITLE
깃허브 라벨 만들기

### ISSUE THREAD

**Issue by wjdals83** [Air-Clean/airclean-spring#18]
# ☘️#이슈번호. 깃허브 라벨 만들기

### 업무구분
>라벨 만들기

### 기능구분
>라벨 만들기

- [x] 1. 여러 이슈 상황에 맞는 라벨 제작하기

##### 부가설명
>부가설명

**Comment by rraaccoon** [comment]
# 언제 만들어주실거에요?
